Models/CityViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace ASPNET8.Models;

public class CityViewModel
{
    [Required]
    public string CityName { get; set; }
}

Models/ErrorViewModel.cs
namespace ASPNET8.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Index.cs
using System.ComponentModel.DataAnnotations;

namespace ASPNET8.Models;

public class Index
{
    [Required]
    public string CityName { get; set; }
}

Models/Product.cs
namespace ASPNET8.Models;

public class Product
{
    public int ID { get; set; }
    public string Name { get; set; }
    public decimal Price { get; set; }
    public DateTime CreatedDate { get; set; }
}

Models/WeatherForecast.cs
namespace ASPNET8.Models;

public class WeatherForecast
{
    public IList<Weather> weather { get; set; }
    public Main main { get; set; }
    //meters
    public int visibility { get; set; }
    public Wind wind { get; set; }
    public Clouds clouds { get; set; }
}

public class Weather
{
    public int id { get; set; }
    public string main { get; set; }
    public string description { get; set; }
    public string icon { get; set; }
}

public class Main
{
    public float temp { get; set; }
    public float feels_like { get; set; }
    public int humidity { get; set; }
}

public class Wind
{
    public float speed { get; set; }
    public int deg { get; set; }
    public float gust { get; set; }
}

public class Clouds
{
    public int all { get; set; }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using ASPNET8.Models;

namespace ASPNET8.Controllers;

public class HomeController : Controller
{
    public IActionResult Index()
    {
        var products = new List<Product>
        {
            new() { ID = 1, Name = "Apple", Price = 4, CreatedDate = DateTime.Now },
            new() { ID = 2, Name = "Banana", Price = 6, CreatedDate = DateTime.Now },
            new() { ID = 3, Name = "Orange", Price = 9, CreatedDate = DateTime.Now }
        };

        return View(products);
    }
}

Controllers/WeatherForecastController.cs
using ASPNET8.Models;
using ASPNET8.Services;
using Microsoft.AspNetCore.Mvc;
using Index = ASPNET8.Models.Index;

// ReSharper disable All

namespace ASPNET8.Controllers;

public class WeatherForecastController : Controller
{
    private readonly WeatherForecastService _weatherForecastService;
    public WeatherForecastController(WeatherForecastService weatherForecastService)
    {
        _weatherForecastService = weatherForecastService;
    }

    public ViewResult Index()
    {
        return View();
    }
    [HttpPost]
    public async Task<IActionResult> GetForecast(CityViewModel model)
    {
        if (!ModelState.IsValid)
        {
            return View("Index");
        }

        try
        {
            Console.WriteLine(model.CityName);
            var forecast = await _weatherForecastService.GetForecastAsync(model.CityName);
            ViewBag.City = model.CityName;
            return View("GetForecast", forecast);
        }
        catch (Exception ex)
        {
            ModelState.AddModelError(string.Empty, $"Error getting forecast: {ex.Message}");
            return View("Index");
        }
    }
}

Views/Shared/Components/ProductsTableViewComponent.cs
using ASPNET8.Models;
using Microsoft.AspNetCore.Mvc;

namespace ASPNET8.Views.Shared.Components;

public class ProductsTableViewComponent : ViewComponent
{
    public IViewComponentResult Invoke(List<Product> products)
    {
        return View(products);
    }
}

Views/Home/Index.cshtml
@model List<Product>

<h2>Список продуктів:</h2>
//lb9
@await Component.InvokeAsync("ProductsTable", new { products = Model })

@* <h2>Список продуктів:</h2> *@
@* <ul> *@
@*     @foreach (var product in Model) *@
@*     { *@
@*         <li>#@product.ID @product.Name - @product.Price$ (@product.CreatedDate)</li> *@
@*     } *@
@* </ul> *@
@* *@
@* <h2>Таблиця продуктів:</h2> *@
@* <table> *@
@*     <thead> *@
@*     <tr> *@
@*         <th>ID</th> *@
@*         <th>Name</th> *@
@*         <th>Price</th> *@
@*         <th>Created Date</th> *@
@*     </tr> *@
@*     </thead> *@
@*     <tbody> *@
@*     @foreach (var product in Model) *@
@*     { *@
@*         <tr> *@
@*             <td>@product.ID</td> *@
@*             <td>@product.Name</td> *@
@*             <td>@product.Price$</td> *@
@*             <td>@product.CreatedDate</td> *@
@*         </tr> *@
@*     } *@
@*     </tbody> *@
@* </table> *@
<style>
    table{
        width: 30%;
    }
    td,th{
        padding: 1%;
        margin: 1%;
        text-align: center;
        border: 1px solid black;
    }
</style>

Views/Shared/AdditionalDataCardPartialView.cshtml
@model WeatherForecast
<div class="card">
    <div class="card-body">
        <p class="card-text">
            <strong>Cloudiness:</strong> @Model.clouds?.all % <br/>
            <strong>Visibility:</strong> @((double)Model.visibility / 1000) km
        </p>
    </div>
</div>

Views/Shared/Components/ProductsTable/Default.cshtml
@model List<Product>

<table>
    <thead>
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Price</th>
        <th>Created Date</th> 
    </tr>
    </thead>
    <tbody>
    @foreach (var product in Model)
    {
    <tr>
        <td>@product.ID</td>
        <td>@product.Name</td>
        <td>@product.Price</td>
        <td>@product.CreatedDate</td>
    </tr>
    }
    </tbody>
</table>

Views/Shared/TemperatureCardPartialView.cshtml
@model Main
<div class="card">
    <div class="card-body">
        <p class="card-text">
            <strong>Temperature:</strong> @((Model?.temp - 273.15 ?? 0.0).ToString("0.00")) °C <br/>
            <strong>Feels like:</strong> @((Model?.feels_like - 273.15 ?? 0.0).ToString("0.00")) °C <br/>
            <strong>Humidity:</strong> @Model?.humidity %
        </p>
    </div>
</div>

Views/Shared/WindCardPartialView.cshtml
@model WeatherForecast
<div class="card">
    <div class="card-body">
        <p class="card-text">
            <strong>Wind speed:</strong> @Model.wind?.speed m/s <br/>
            <strong>Wind direction:</strong> @Model.wind?.deg ° <br/>
            <strong>Gust:</strong> @Model.wind?.gust m/s
        </p>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - ASPNET8</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/ASPNET8.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ASPNET8</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - ASPNET8 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/WeatherForecast/GetForecast.cshtml
@model ASPNET8.Models.WeatherForecast


<h1 class="m-auto text-center p-3 mb-2 bg-light text-black-50 w-50" style="font-size:2.5em;">Weather Forecast for @ViewBag.City!</h1>

<div class="card w-50 m-auto">
    <div class="card-body">
        <h5 class="card-title" style="font-size:1.5em;">@Model.weather[0]?.main</h5>
        <h6 class="card-subtitle mb-2 text-muted">@Model.weather[0]?.description</h6>

        <div class="card-deck">
            @{
                await Html.RenderPartialAsync("TemperatureCardPartialView", Model.main);
            }

            @{
                await Html.RenderPartialAsync("WindCardPartialView", Model);
            }

            @{
                await Html.RenderPartialAsync("AdditionalDataCardPartialView", Model);
            }
        </div> 
    </div> 
</div> 

Views/WeatherForecast/Index.cshtml
@model ASPNET8.Models.CityViewModel

@{
Layout = Layout;
}

<div class="card">
    <div class="card-body">
        <form method="post" asp-action="GetForecast">
            <div class="form-group">
                <label for="cityName">Enter the city name:</label>
                <input id="cityName" name="CityName" asp-for="CityName" required class="form-control"/>
            </div>
            <button type="submit" class="btn btn-dark">Submit</button>
        </form>
    </div>
</div>

<style>
    .card {
        max-width: 600px;
        margin: auto;
        padding: 20px;
    }

    .form-group {
        margin-bottom: 15px;
    }
</style>